import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./_components/common/header/header";
import AuthContext from "./_components/context/authContext";
import ToasterContext from "./_components/context/toasterContext";
import SignupModal from "./_components/common/modals/signupModal";
import LoginModal from "./_components/common/modals/loginModal";
import getCurrentUser from "./actions/getCurrentUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <AuthContext>
          <ToasterContext />
          <SignupModal />
          <LoginModal />
          <Header currentUser={currentUser} />
          {children}
        </AuthContext>
      </body>
    </html>
  );
}
