import type { Metadata } from "next";
import AuthContext from "./_components/context/auth-context";
import ToasterContext from "./_components/context/toaster-context";
import getCurrentUser from "./_feature/actions/getCurrentUser";
import { Header } from "./_components/common/header";
import SignupModal from "./_components/common/modals/signup-modal";
import LoginModal from "./_components/common/modals/login-modal";
import { Footer } from "./_components/common/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <AuthContext>
          <ToasterContext />
          <SignupModal />
          <LoginModal />
          <Header currentUser={currentUser} />
          {children}
          <Footer />
        </AuthContext>
      </body>
    </html>
  );
}
